version: '3'
services:
  tts:
    build: .
    ports:
      - "5002:5002"
    command: ["--model_name", "tts_models/multilingual/multi-dataset/your_tts", "--use_cuda", "false"]
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
